### ISSUE TITLE
Problem Merging SVs of 10X with delly, lumpy and breakdancer.

### ISSUE THREAD

**Issue by unique379r** [fritzsedlazeck/SURVIVOR#81] opened 2019-04-05 15:41 UTC
HI Fritz,

I try to merge vcfs from 10X, delly, lumpy and breakdancer but  seems its not working as expected. 

**SURVIVOR Version: 1.0.7**

```
Breakdancer:
chr19	19049089	.	.	.	.	PASS	PROGRAM=breakdancer;SVTYPE=DUP;SVLEN=304826;END=19353915	GT:DP	1/.:0
Delly: 
chr19	19010583	DUP00041058	T	<DUP>	.	PASS	IMPRECISE;SVTYPE=DUP;SVMETHOD=EMBL.DELLYv0.7.8;CHR2=chr19;END=19336493;PE=35;MAPQ=60;CT=5to3;CIPOS=-1402,1402;CIEND=-1402,1402	GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV	0/1:-258.088,0,-318.193:10000:PASS:2223:6586:2171:3:59:50:0:0
Lumpy:
chr19	19010582	134213	N	<DUP>	.	.	SVTYPE=DUP;STRANDS=-+:34;SVLEN=325909;END=19336491;CIPOS=0,0;CIEND=0,0;CIPOS95=-321,2;CIEND95=-2,658;IMPRECISE;SU=34;PE=34;SR=0	GT:SU:PE:SR	./.:34:34:0
TenX:
chr19	19010558	call_285_1	G	]chr19:19336749]G	23	PASS	CIPOS=-7,7;SVTYPE=BND;SVTYPE2=DUP;PS=19014659;MATEID=call_285_2;EVENT=call_285;HAP_ALLELIC_FRAC=1.0;ALLELIC_FRAC=0.022977022977;PAIRS=15;SPLIT=1;WildCov=.;MolTtl=.;MolTtlNoR=.;MolDel=.;MolDelNoR=.;MolWild=.;MolWildNoR=.;PVAL=.;BGSize=.;BGImparityPval=.;BGTtlRCnt=.;BGHP1RCnt=.;BGHP2RCnt=.;BGBaseCov=.;BGPhaseFrac=.;NRead=.;SOURCE=CNV,SV	GT	1|1

Commands:
SURVIVOR merge Sample 1000 2 1 0 0 50 BDL_MP10X_2.vcf

Expected output should have all of them but SURVIVOR took only entry of delly and lumpy.

chr19	19010582	134213	N	<DUP>	.	PASS	SUPP=2;SUPP_VEC=0011;SVLEN=325910;SVTYPE=DUP;SVMETHOD=SURVIVOR1.0.6;CHR2=chr19;END=19336491;CIPOS=0,1;CIEND=0,2;STRANDS=-+	GT:PSV:LN:DR:ST:QV:TY:ID:RAL:AAL:CO	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	0/1:NA:325910:109,0:-+:.:DUP:DUP00041058:NA:NA:chr19_19010583-chr19_19336493	./.:NA:325909:0,34:-+:.:DUP:134213:NA:NA:chr19_19010582-chr19_19336491

Reason could be: I suspect that SURVIVOR reads the input CHR, START, END, SVTYPE AND SVLEN and in case of 10X vcf, it has only chr and end which could be a reason SURVIVOR decided to skip, is it ?? Even though Size of SVs are around the 1K base in each tool.

but some 10X vcf has those entry and it has been merged:

chr2	174961946	INV00006063	C	<INV>	18	PASS	SUPP=3;SUPP_VEC=1011;SVLEN=2352715;SVTYPE=INV;SVMETHOD=SURVIVOR1.0.6;CHR2=chr2;END=177314937;CIPOS=-64,0;CIEND=-875,0;STRANDS=--	GT:PSV:LN:DR:ST:QV:TY:ID:RAL:AAL:CO	0|1:NA:2352180:0,0:++:18:INV:call_314_1:NA:NA:chr2_174961882-chr2_177314062	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	0/1:NA:2352991:91,0:--:.:INV:INV00006063:NA:NA:chr2_174961946-chr2_177314937	./.:NA:2352973:0,5:--:.:INV:19715_1:NA:NA:chr2_174961916-chr2_177314889
```

But i wonder why breakdancer is not integrated ?

I also tried with only MP data (breakdancer, delly and lumpy) but still breakdancer entry is lacking in the integrated calls by SURVIVOR.

```
SURVIVOR merge MPSample 1000 2 1 0 0 50 BDL_MP2.vcf

chr19	19010582	134213	N	<DUP>	.	PASS	SUPP=2;SUPP_VEC=011;SVLEN=325910;SVTYPE=DUP;SVMETHOD=SURVIVOR1.0.7;CHR2=chr19;END=19336491;CIPOS=0,1;CIEND=0,2;STRANDS=-+	GT:PSV:LN:DR:ST:QV:TY:ID:RAL:AAL:CO	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	0/1:NA:325910:109,0:-+:.:DUP:DUP00041058:NA:NA:chr19_19010583-chr19_19336493	./.:NA:325909:0,34:-+:.:DUP:134213:NA:NA:chr19_19010582-chr19_19336491
```

```
SURVIVOR merge MPSample 1000 3 1 0 0 50 BDL_MP3.vcf

got ZERO entry.

```
Please advice, waiting for your kind reply

PS: By the way this DUP entry is control event that has been predicted by all tools and we wanted to see them into our merge call but it seems  SURVIVOR is not taking into account.

Regards
Rupesh

**Comment by fritzsedlazeck** [comment] 2019-04-05 15:49
Hi Rupesh,
thanks for reaching out. I think there are multiple points.
1.  The reason is that the 10x call do not correspond in type:
]chr19:19336749]G
nor for the end coordinate: 19014659 (vs. Delly + Lumpy agreeing on the end position ~ 19336491) 

2. Furthermore, check if the input file `MPSample` has no empty lines and includes the Breakdance file. Looks like its not recognized from the output you showed. 

I hope that helps. Keep me posted.

Thanks
Fritz

**Comment by unique379r** [comment] 2019-04-05 16:02
Thanks Fritz for your quick reply.

Point 1: Any recommendations ? should i have to reformat the original vcf of 10X ? or something better option I could try ? As i mentioned 10X has some entry such that SURVIVOR takes but not all of them.

Point 2. I guess, SURVIVOR recognized it, if you see genotype entries in integrated call. 

```
From above entry of integrated call of MPsample.

## brekadancer
/.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	0/1:NA:325910:109,0:-

## Delly
+:.:DUP:DUP00041058:NA:NA:chr19_19010583-chr19_19336493

## lumpy
./.:NA:325909:0,34:-+:.:DUP:134213:NA:NA:chr19_19010582-chr19_19336491

```

NOTE: by the way, I checked there is not empty lines. But reason i suspect may be order of entries are changed within breakdancer compare of delly and lumpy ?? This is just my assumption, if your code taking entry based on columns setting from vcf.

**Comment by fritzsedlazeck** [comment] 2019-04-05 16:11
Hi,
ok sorry I thought your SUPP_VEC was only 3 diggits so that is fine. 
The problem is that SURVIVOR merge looks at the start and stop coordinates. Here these do not correspond with each other given the thresholds you specified.

`SURVIVOR merge MPSample 1000 2 1 ..`
You are asking here to allow a maximum of 1000 bp to be different between the start or the stop coordinate and you are asking to be type specific. Both are violated since 10x genomics specifies 
`SVTYPE=BND`

And breakdance has a different start: 19049089 vs 19010583.
Also 10x has a different stop: 19014659 vs 19336491

So you could try to extend this 1000 threshold and dont require Type specific merges and see if that helps. I am just worried that you will lump together a lot of variants. 

`SURVIVOR merge MPSample 40000 2 0 ..` . 
I frankly **would not do that.**..
 I would ask if breakdancer is actually calling the right DUP??  
Same for 10x genomics: 322kbp apart! 

Do you know the location of the DUP since it is a control?

This probably does not help much on what you want to acchieve, but I hope you get a better insight why you are not getting the results you expect. 

Cheers
Fritz

**Comment by unique379r** [comment] 2019-04-05 18:07
Hi ,

1. 
SURVIVOR merge MPSample 1000 2 1 ..
You are asking here to allow a maximum of 1000 bp to be different between the start or the stop coordinate and you are asking to be type specific. Both are violated since 10x genomics specifies
SVTYPE=BND

Comment: Can be true but here 10X has another "SVTYPE2=DUP" which is, I suppose no means for SURVIVOR.

```
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##INFO=<ID=SVTYPE2,Number=1,Type=String,Description="Type of structural variant implied by breakends">
```

2.
And breakdance has a different start: 19049089 vs 19010583. ==> AGREE

Also 10x has a different stop: 19014659 vs 19336491  == PS is actually not a END in 10X, END co-ordinate is "19336749" which is very close to lumpy and delly. But again i guess lacking of "END" tag cause the problem for SURVIVOR.

`##INFO=<ID=PS,Number=1,Type=Integer,Description="Phase set assignment">`

3.
So you could try to extend this 1000 threshold == I can but, same fear I also have that I would end-up with lot of variants.

dont require Type specific merges and see if that helps == I can't, since its not right way to do, i guess. Also you have suggested **would not do that..**.

4.
I would ask if breakdancer is actually calling the right DUP??

You are right actually !! It was unknown type but visualizing via IGV lead me to change this into DUP type.

5. 
Same for 10x genomics: 322kbp apart!

It is actually true, I have seen by their loupe (find the attachment) and IGV using bam.
![DUP_10X](https://user-images.githubusercontent.com/41694905/55647485-c9500700-57ab-11e9-906b-b208104a020d.png)

6.
Do you know the location of the DUP since it is a control?

`C57BL/6J-Rorb	chr19	19,010,565	19,336,747	DUP	300kb`

Thanking you for your explanations and time.
Rupesh

**Comment by fritzsedlazeck** [comment] 2019-04-05 22:21
Hi Rupesh,
At 1) Yes SVType2 is not considered. Its the first time I see someone specify two different SVTypes...

At 2)  Ah you are right @10x . It should merge it, but the types are different and I think you ask for the matching types. 

At 3) Try it. (No type save matches). As long as you keep the 1kbp distance it should not be bad. 

At 5) Yes that was me being stupid and not look at the BND notation. 

We are getting there :)
Cheers
Fritz

**Comment by unique379r** [comment] 2019-04-06 00:47
Thanks Fritz for your time
@3. 
Ok will try that  (No type save matches) but also I am trying to convert 10X vcf to format as other vcf so that SURVIVOR can take it.
Lets see what works for me, will update you soon.

**Comment by unique379r** [comment] 2019-04-08 15:46
Hi Fritz,
Just a quick question about SURVIVOR merge.

Does Order of tags are matters in VCF while using SURVIVOR merge? Since survivor requires START, END, SVTYPE and SVLEN.

```
Lets say 

## breakdancer
chr19	19049089	.	.	.	.	PASS	PROGRAM=breakdancer;SVTYPE=DUP;SVLEN=304826;END=19353915	GT:DP	1/.:0

Can be (just converted tenX vcf similar to breakdancer)

chr1	3390039	call_2587_1	A	<DUP>	3	LOWQ	PROGRAM=TenX;END=3445262;SVLEN=55223;SVTYPE=DUP	GT	1|1
chr1	3445262	call_2587_2	T	<DUP>	3	LOWQ	PROGRAM=TenX;END=3390039;SVLEN=-55223;SVTYPE=DUP	GT	1|1
```

Thanks Rupesh

**Comment by fritzsedlazeck** [comment] 2019-04-08 16:05
No the order should not matter within the INFO field. 
Thats what you are asking right?
Cheers
Fritz

**Comment by unique379r** [comment] 2019-04-08 19:13
Yes that i was asking....

```
Now finally its working 👍 i.e SURVIVOR merge is now able to take 10X, delay and lumpy within 1K base apart of SVs.

chr19	19010558	call_285_1	G	<DUP>	23	PASS	SUPP=3;SUPP_VEC=0111;SVLEN=326003;SVTYPE=DUP;SVMETHOD=SURVIVOR1.0.7;CHR2=chr19;END=19336749;CIPOS=0,25;CIEND=-258,0;STRANDS=-+	GT:PSV:LN:DR:ST:QV:TY:ID:RAL:AAL:CO	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	0/1:NA:325910:109,0:-+:.:DUP:DUP00041058:NA:NA:chr19_19010583-chr19_19336493	1|1:NA:326191:0,0:-+:23:DUP:call_285_1:NA:NA:chr19_19010558-chr19_19336749	./.:NA:325909:0,34:-+:.:DUP:134213:NA:NA:chr19_19010582-chr19_19336491

```

Thanks Fritz for informative discussion and guidance.

Rupesh

**Comment by fritzsedlazeck** [comment] 2019-04-08 19:16
Awesome. Thanks for keeping me posted. 
I will close the issue now. 
Cheers
Fritz

**Closed by fritzsedlazeck** 2019-04-08 19:16 UTC

**Comment by unique379r** [comment] 2019-04-08 20:27
Another updates:
By the way i tired with NO SVTYPE option and end-up with around 100 of SVs more integrated than converted vcf.
Plus i found difference between without SVTYPE  and with SVTYPE (using modified vcf) is that both have different START and END coordinates.

```
NO SVTYPE (from original vcf)
Number of integrated vcf: 5281
# start and end taken from lumpy
samples list: 
10XSV.sort.vcf
breakDRorb_hstp_GT17-02247-MP.vcf
dellyRorb_hstp_GT17-02247-MP.vcf
lumpyRorb_hstp_GT17-02247-MP.vcf

chr19	19010583	DUP00041058	T		<DUP>	23	PASS	SUPP=3;SUPP_VEC=1011;SVLEN=326003;SVTYPE=DUP;SVMETHOD=SURVIVOR1.0.7;CHR2=chr19;END=19336493;CIPOS=-25,0;CIEND=-2,256;STRANDS=-+	GT:PSV:LN:DR:ST:QV:TY:ID:RAL:AAL:CO	1|1:NA:326191:0,0:++:23:INV:call_285_1:NA:NA:chr19_19010558-chr19_19336749	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN 0/1:NA:325910:109,0:-+:.:DUP:DUP00041058:NA:NA:chr19_19010583-chr19_19336493	./.:NA:325909:0,34:-+:.:DUP:134213:NA:NA:chr19_19010582-chr19_19336491

With SVTYPE (modified vcf)
Number of integrated vcf: 5185
# start and end taken from 10X
samples list: 
breakDRorb_hstp_GT17-02247-MP.vcf
dellyRorb_hstp_GT17-02247-MP.vcf
lumpyRorb_hstp_GT17-02247-MP.vcf
refromated_Ten10X.sort.vcf

chr19	19010558	call_285_1	G	<DUP>	23	PASS	SUPP=3;SUPP_VEC=0111;SVLEN=326003;SVTYPE=DUP;SVMETHOD=SURVIVOR1.0.7;CHR2=chr19;END=19336749;CIPOS=0,25;CIEND=-258,0;STRANDS=-+	GT:PSV:LN:DR:ST:QV:TY:ID:RAL:AAL:CO	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	0/1:NA:325910:109,0:-+:.:DUP:DUP00041058:NA:NA:chr19_19010583-chr19_19336493	1|1:NA:326191:0,0:-+:23:DUP:call_285_1:NA:NA:chr19_19010558-chr19_19336749	./.:NA:325909:0,34:-+:.:DUP:134213:NA:NA:chr19_19010582-chr19_19336491
```

Any idea why it is so ? I know it is not big difference in numbers as well as coordinates since it is set to 1K bp distance but i just want to know why it is happening ? 
is it based on sample list or any specific reason ?

Thanks

**Comment by fritzsedlazeck** [comment] 2019-04-08 20:31
Hi,
can you explain what you mean: "100 of SVs more integrated than converted vcf."

About the different locations: yes they are slightly different because it is always a best guess from all the evidence but a real coordinate. You can see that different sets were merged and also 3 calls. So it can change slightly, which it does.
What it does under the hood is to compute which of the locations is the median location for the start and it chooses this as a representative. 

Makes sense?
Cheers
Fritz

**Comment by unique379r** [comment] 2019-04-08 20:48
Yes Fritz that makes sense thanks for your expansions. 

And about number, I mean when i used NO SVTYPE on original vcf + delay and lumpy+breakdancer, i got more integrated vcfs (i guess, its because of no accurate SVTYPE has matched). 
1. case 1 (NO SVTYPE has chosen and used original 10X vcf)
Number of integrated vcf: 5281

1. case 2 (SVTYPE has chosen and used modified 10X vcf)
Number of integrated vcf: 5185

5281-5185 = 96

I tired with only one sample and i am afraid that number can be increased in another samples. Since i have to merge around 60 samples.

Rupesh.

**Comment by fritzsedlazeck** [comment] 2019-04-08 20:53
There can be some hickups wiht unsorted files. I usually only see them in larger populations. 
Maybe this is what you are running into. 
Thanks for pointing it out. 
Fritz
